[TSS]
TURRETS = [
  'GAO42ZAO6LSM2RMPXS5F5YSNT7YIZLTUAE647JQFJLOOHONSTXQTTSFM', # self
  'GB4OYM7TQTJSROWXHOJLKAX2IJ2QN4I6S6GCJH4MGWVTAO5Q5DPNADXX', # tyvdh
  'GAMGW7ZESFF2KVGL7EMBBIAXTFAOF3MNI2JBWSPLTGMAKOSVLHDNZMA2', # EverLife.AI
  'GBN5WKCKLEDOXREUX5QWCJZIMMHJC2X4KK4FJS327PF3G3ED57A7GZSK', # Script3
  'GARBNUK4IZDGKDJTIEWAL6FTY3UDRSRV275X4H5JS2PGCKTZZ3NDYU5U', # Litemint
  'GDZACR7XAJWU3JLJ5TVDOLCVB5DCIY2K7PHDR7ODGCEQTNVENOPHLCF7', # Atemosta
  'GA7FCNDCYS2N4XQER6P2KHK4FDVVM2PJCM3PODAZXC35QNJR5WINT6GO', # Zig3
  'GATCMFLSJYFQ3XVNMHXKWHVUYKGQ4FDRD6U7VXSDEIUDI7MVTK2SON5Q', # Ralphilius
  'GBUJG6HXFHTD65OOZJGIUO6D35XCY3LW75DUWJB262CTDTJHOUHVHWHW', # Anclap
]